// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deleteDocument.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM  documents
WHERE id=$1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}
