// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, created_at, updated_at, external_id,external_key,filename,status,request_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, external_id, external_key, filename, status, request_id, err_message
`

type CreateDocumentParams struct {
	ExternalID  string
	ExternalKey sql.NullString
	Filename    sql.NullString
	Status      string
	RequestID   uuid.UUID
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ExternalID,
		arg.ExternalKey,
		arg.Filename,
		arg.Status,
		arg.RequestID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.ExternalKey,
		&i.Filename,
		&i.Status,
		&i.RequestID,
		&i.ErrMessage,
	)
	return i, err
}
