// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getDocument.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDocument = `-- name: GetDocument :one
SELECT id, created_at, updated_at, external_id, external_key, filename, status, request_id
FROM documents
WHERE id=$1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.ExternalKey,
		&i.Filename,
		&i.Status,
		&i.RequestID,
	)
	return i, err
}
