// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getDocumentUser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDocumentUser = `-- name: GetDocumentUser :one
SELECT users.id
FROM users 
JOIN requests ON requests.user_id = users.id 
JOIN documents ON documents.request_id = requests.id
WHERE documents.id = $1
`

func (q *Queries) GetDocumentUser(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getDocumentUser, id)
	err := row.Scan(&id)
	return id, err
}
