// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getRequestDocument.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDocumentProvider = `-- name: GetDocumentProvider :one
SELECT requests.id,provider
FROM requests
JOIN documents ON documents.request_id = requests.id
WHERE documents.id = $1
`

type GetDocumentProviderRow struct {
	ID       uuid.UUID
	Provider string
}

func (q *Queries) GetDocumentProvider(ctx context.Context, id uuid.UUID) (GetDocumentProviderRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentProvider, id)
	var i GetDocumentProviderRow
	err := row.Scan(&i.ID, &i.Provider)
	return i, err
}
