// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getRequest.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getRequest = `-- name: GetRequest :one
SELECT id, created_at, updated_at, provider, req_type, from_lang, to_lang, user_id
FROM requests
WHERE id=$1
`

func (q *Queries) GetRequest(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ReqType,
		&i.FromLang,
		&i.ToLang,
		&i.UserID,
	)
	return i, err
}
