// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs (id, created_at, updated_at, is_successful,cached,error,request_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, is_successful, cached, error, request_id
`

type CreateLogParams struct {
	IsSuccessful bool
	Cached       bool
	Error        sql.NullString
	RequestID    uuid.UUID
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createLog,
		arg.IsSuccessful,
		arg.Cached,
		arg.Error,
		arg.RequestID,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuccessful,
		&i.Cached,
		&i.Error,
		&i.RequestID,
	)
	return i, err
}
