// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (id, created_at, updated_at, provider,req_type,from_lang,to_lang,user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, provider, req_type, from_lang, to_lang, user_id
`

type CreateRequestParams struct {
	Provider string
	ReqType  string
	FromLang string
	ToLang   string
	UserID   uuid.UUID
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, createRequest,
		arg.Provider,
		arg.ReqType,
		arg.FromLang,
		arg.ToLang,
		arg.UserID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ReqType,
		&i.FromLang,
		&i.ToLang,
		&i.UserID,
	)
	return i, err
}
