// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateUser.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2 , hashed_password = $3 , is_admin = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, email, is_admin, hashed_password
`

type UpdateUserParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword sql.NullString
	IsAdmin        bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.HashedPassword,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.IsAdmin,
		&i.HashedPassword,
	)
	return i, err
}
