// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateDocument.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET status = $2 ,err_message = $3 , updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, external_id, external_key, filename, status, request_id, err_message
`

type UpdateDocumentParams struct {
	ID         uuid.UUID
	Status     string
	ErrMessage sql.NullString
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocument, arg.ID, arg.Status, arg.ErrMessage)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.ExternalKey,
		&i.Filename,
		&i.Status,
		&i.RequestID,
		&i.ErrMessage,
	)
	return i, err
}
