GET http://localhost:8080/api/health HTTP/1.1

###

POST http://localhost:8080/api/deepl/translate HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIyMzk5N2I1ZS1lY2ZkLTQzNjctOTdjMS1hOWY4ZWJjZTQxZDciLCJleHAiOjE3NzI3MjgwMzksImlhdCI6MTc3MjcyNDQzOX0.3lkzHTXSyJAATMHF2WRabjiUjEMPaHFoZER6dUzndNo

{
    "provider": "DeepL",
    "text": ["hello my name is 0n1x"],
    "source_lang": "EN",
    "target_lang": "ZH-HANT"
}

###

POST http://localhost:8080/api/translate HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIyMzk5N2I1ZS1lY2ZkLTQzNjctOTdjMS1hOWY4ZWJjZTQxZDciLCJleHAiOjE3NzI3NTEzMTcsImlhdCI6MTc3Mjc0NzcxN30.4VHTVc_BpLzKKZcnuN3bGoqv9jWp6wi2kHxgKpV1d9A

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

Hello world this is a test fil.
------WebKitFormBoundary
Content-Disposition: form-data; name="source_lang"

EN
------WebKitFormBoundary
Content-Disposition: form-data; name="provider"

DeepL
------WebKitFormBoundary
Content-Disposition: form-data; name="target_lang"

JA
------WebKitFormBoundary--


###

GET http://localhost:8080/api/documents/64bf6edc-53c0-4574-bd97-f4b6a7760189
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiJjNDcyOTRmMS1jOWRmLTRiMmMtOWYxMi1lYzg4OTk4MThmOGMiLCJleHAiOjE3NzI3NTE1NzEsImlhdCI6MTc3Mjc0Nzk3MX0.qn4UDvzyvOj8S2Yh7wO5VC8NZD2M4PC9stHFvhJO2QM

###

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email" : "0n1x",
    "password" : "0n1x"
}

###

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email" : "user",
    "password" : "password"
}

###

POST http://localhost:8080/api/admin/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIyMzk5N2I1ZS1lY2ZkLTQzNjctOTdjMS1hOWY4ZWJjZTQxZDciLCJleHAiOjE3NzI3NTEzMTcsImlhdCI6MTc3Mjc0NzcxN30.4VHTVc_BpLzKKZcnuN3bGoqv9jWp6wi2kHxgKpV1d9A


{
    "email" : "user",
    "password" : "password"
}

###

GET http://localhost:8080/api/admin/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiI5ZmNmNTdhMy0xNjdlLTRjNjktYTEyZS1mZTc5MTI4NThhOGYiLCJleHAiOjE3NzAxNDcwMDUsImlhdCI6MTc3MDE0MzQwNX0.YemmL7aBQlaTseTb67ecBs2xgxlO-xIBWBxOTAHdcRQ

###

DELETE http://localhost:8080/api/admin/users/7dc4bf02-5d31-46e3-b42c-808350f1ab8c HTTP/1.1
Authorization: Bearer 

{
    "email" : "newuser",
    "password" : "password",
    "is_admin" : false
}